name: Dispatcher
control:
   mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_Dispatcher_to_QC-TASK-RUNNER-daqTask"
    type: "push"
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/home/test/ControlWorkflows/alice/sw/MODULES/slc7_x86-64 module load QualityControl &&
    MODULEPATH=/home/test/ControlWorkflows/alice/sw/MODULES/slc7_x86-64 module load Control-OCCPlugin &&
    MODULEPATH=/home/test/ControlWorkflows/alice/sw/MODULES/slc7_x86-64 module list &&
    o2-qc-run-readout -b | o2-qc-run-qc
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "no-op://"
    - "--id"
    - "Dispatcher"
    - "--log-color"
    - "false"
    - "--config"
    - "json:///etc/flp.d/qc/readout.json"

