name: fairmq-ex-copypush-sink
control:
  mode: fairmq
wants:
  cpu: 0.1
  memory: 128
bind: []
properties:
  severity: trace
  color: false
command:
  env: []
  shell: true
  arguments: []
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/home/test/ControlWorkflows/alice/sw/MODULES/slc7_x86-64 module load FairMQ &&
    MODULEPATH=/home/test/ControlWorkflows/alice/sw/MODULES/slc7_x86-64 module load Control-OCCPlugin &&
    fairmq-ex-copypush-sink
