name: fairmq-ex-multiple-channels-broadcaster
control:
  mode: fairmq
wants:
  cpu: 0.1
  memory: 128
bind:
- name: "broadcast"
  type: "pub"
  sndBufSize: 1000
  rcvBufSize: 1000
  rateLogging: 0
properties:
  severity: trace
  color: false
command:
  env: []
  shell: true
  arguments: []
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/home/test/ControlWorkflows/alice/sw/MODULES/slc7_x86-64 module load FairMQ &&
    MODULEPATH=/home/test/ControlWorkflows/alice/sw/MODULES/slc7_x86-64 module load Control-OCCPlugin &&
    fairmq-ex-multiple-channels-broadcaster
