name: readout # read by workflow
control:
  mode: direct
wants:
  cpu: 0.15
  memory: 128
bind: []
properties: {}
command: 
  env: []
  shell: true
  arguments:
    - "file:/home/flp/readout.cfg"
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/home/test/alice/sw/MODULES/slc7_x86-64 module load Readout &&
    MODULEPATH=/home/test/alice/sw/MODULES/slc7_x86-64 module load Control-OCCPlugin &&
    readout.exe
